### ISSUE TITLE
Upload needs to be run twice for updates to take place

### ISSUE THREAD

**Issue by davidpesce** [alexandru-elisei/moodle-tool_uploadusercli#1]
Using the following command:
`
php uploadusercli.php --mode=createorupdate --updatemode=dataonly --file=/root/upload-today.csv
`
It takes running it twice for the update portion of it to take effect. So it'll create new users on the first pass, but doesn't include custom fields. Running it the second time, updates the custom fields.

**Comment by alexandru-elisei** [comment]
Can you post a few lines from the CSV file that triggers this behaviour, so I can reproduce the issue?

I take it that this only happens when you create users with custom defined fields, am I correct?

**Comment by davidpesce** [comment]
Sorry I didn't get back to this sooner. I'll give it a whirl and make sure it's ok. Thank you!!

**Comment by alexandru-elisei** [comment]
No problem, I tested the fix before pushing the commit, but if you find that the issue still isn't fixed please let me know.
