### ISSUE TITLE
Existing user details - Override with file (updatemode = dataonly)

### ISSUE THREAD

**Issue by davidpesce** [alexandru-elisei/moodle-tool_uploadusercli#2]
I'm curious if the updatemode = dataonly is equivalent to Moodle's 'Override with file' - https://docs.moodle.org/29/en/Upload_users#Existing_user_details

I'm using the dataonly updatemode and it's overwriting existing data, but doesn't remove information that isn't in the file. For example, if a users name changes, that is overwritten. If there's a field that is left out of the next import, it's not removed from the user profile. 

Is this how it's supposed to work?

If it is, is there a way to make it work the way I'd like? (Basically wipes out any data that isn't included in the file, each time the file is imported). I'm pulling data from an HR system that has a lot of changes and would like to make sure they stay in sync.

**Comment by alexandru-elisei** [comment]
Thank you for spotting this, I've created the plugin to have the same functionality as the official moodle uploaduser. I'll look into it.

In the meantime, if you want to replace the user data with the data from the CSV file and not have any of the old data, may I suggest your first delete the users, then create them via the CSV file? It should be easily done by parsing the CSV file with the new data and extracting the username.

Maybe it would be safer to try it on a test user first, though.

**Comment by davidpesce** [comment]
I dug a bit deeper and the way to do this is include blank values for items that need to be wiped out.
